unpackaged/main/default/objects/Case/fields/Pipelines_checkbox__c.field-meta.xml
<CustomField>
    <fullName>Pipelines_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pipelines checkbox</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pipelines_test__c.field-meta.xml
<CustomField>
    <fullName>Pipelines_test__c</fullName>
    <label>Pipelines test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GetCasesForPipelines.cls
public with sharing class GetCasesForPipelines {
    public static void GetCasesForPipelines() {

        List<Case> cases = [SELECT Id, Pipelines_checkbox__c, Pipelines_test__c FROM Case LIMIT 5];

        for (Case cs : cases) {
            cs.Pipelines_checkbox__c = true;
            cs.Pipelines_test__c = 'Hotfixes';
            System.debug('cases ' + cs);
        }
        update cases;

    }
}